name: "CI/CD ECO CLIENT APP"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.1"

      - name: "Install dependencies and build"
        run: |
          npm install
          npm run build

      - name: "Deploy to local server"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_LS }}
          port: 22
          script: |
            # Add server's SSH key to known_hosts to avoid prompt
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

            # Deploy process
            cd /var/www/workers/EcoWaterFrontend/
            git pull --no-rebase origin main
            /usr/bin/npm install
            /usr/bin/npm run build
